name: surfy_mobile_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  go_router: ^14.1.4
  mapbox_maps_flutter: ^2.0.0
  web3auth_flutter: ^4.0.0
  google_fonts: ^6.2.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  web3dart: ^2.7.3
  twitter_login: ^4.4.2
  solana: ^0.30.4
  base_x: ^2.0.1
  crypto: ^3.0.3
  logger: ^2.3.0
  camera: ^0.11.0+1
  dio: ^5.4.3+1
  flutter_native_splash: ^2.4.0
  app_links: ^6.1.1
  dartx: ^1.2.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  geolocator: ^12.0.0
  flutter_swipe_button: ^2.1.3
  url_launcher: ^6.3.0
  qr_code_scanner:
    git:
      url: https://github.com/dola99/qr_code_scanner
      ref: update
  vibration: ^1.9.0
  xrpl_dart: ^4.3.0
  local_auth: ^2.2.0
  tron: ^0.0.2
  grpc: ^3.2.4
  on_chain: ^3.4.0
  blockchain_utils: ^3.1.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_dotenv: ^5.1.0
  gif: ^2.3.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0
  web3dart_builders: ^0.1.2

flutter_launcher_icons:
  android: "launcher_icon"
  min_sdk_android: 21
  ios: true
  image_path: "assets/images/app_ic.png"


flutter_native_splash:
  image: "assets/images/ic_surfy.png"
  color: "#000000"
  android_12:
    image: "assets/images/ic_surfy.png"
    color: "#000000"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - .env
    - assets/images/
    - assets/images/tokens/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
